// <auto-generated />
namespace ThanalSoft.SmartComplex.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserIDchangesinreftables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserIDchangesinreftables));
        
        string IMigrationMetadata.Id
        {
            get { return "201512251628059_UserID changes in ref tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
